import type { GalleryImage } from "./wedding";

// Generated by scripts/prepare-media.mjs from every non-featured JPG/JPEG in media/.
export const allGalleryImages = [
  {
    "id": "archive-045-img-7278",
    "src": "/media/archive/045-img-7278.webp",
    "alt": "Schloss Bückeburg und seine historischen Räume am Hochzeitstag – Aufnahme 045",
    "width": 1333,
    "height": 2000,
    "chapter": "Schloss Bückeburg",
    "layout": "portrait"
  },
  {
    "id": "archive-048-img-7284",
    "src": "/media/archive/048-img-7284.webp",
    "alt": "Schloss Bückeburg und seine historischen Räume am Hochzeitstag – Aufnahme 048",
    "width": 2000,
    "height": 1333,
    "chapter": "Schloss Bückeburg",
    "layout": "standard"
  },
  {
    "id": "archive-049-img-7285",
    "src": "/media/archive/049-img-7285.webp",
    "alt": "Ein Blick auf die besondere Kulisse von Schloss Bückeburg – Aufnahme 049",
    "width": 1333,
    "height": 2000,
    "chapter": "Schloss Bückeburg",
    "layout": "portrait"
  },
  {
    "id": "archive-051-img-7287",
    "src": "/media/archive/051-img-7287.webp",
    "alt": "Schloss Bückeburg und seine historischen Räume am Hochzeitstag – Aufnahme 051",
    "width": 1333,
    "height": 2000,
    "chapter": "Schloss Bückeburg",
    "layout": "portrait"
  },
  {
    "id": "archive-054-img-7293",
    "src": "/media/archive/054-img-7293.webp",
    "alt": "Schloss Bückeburg und seine historischen Räume am Hochzeitstag – Aufnahme 054",
    "width": 1333,
    "height": 2000,
    "chapter": "Schloss Bückeburg",
    "layout": "portrait"
  },
  {
    "id": "archive-056-img-7296",
    "src": "/media/archive/056-img-7296.webp",
    "alt": "Architektur und Schlossgarten rund um die Trauung von Lea und Christoph – Aufnahme 056",
    "width": 2000,
    "height": 1333,
    "chapter": "Schloss Bückeburg",
    "layout": "standard"
  },
  {
    "id": "archive-059-img-7302",
    "src": "/media/archive/059-img-7302.webp",
    "alt": "Architektur und Schlossgarten rund um die Trauung von Lea und Christoph – Aufnahme 059",
    "width": 1572,
    "height": 2000,
    "chapter": "Schloss Bückeburg",
    "layout": "portrait"
  },
  {
    "id": "archive-066-img-7317",
    "src": "/media/archive/066-img-7317.webp",
    "alt": "Schloss Bückeburg und seine historischen Räume am Hochzeitstag – Aufnahme 066",
    "width": 2000,
    "height": 1172,
    "chapter": "Schloss Bückeburg",
    "layout": "standard"
  },
  {
    "id": "archive-069-img-7323",
    "src": "/media/archive/069-img-7323.webp",
    "alt": "Schloss Bückeburg und seine historischen Räume am Hochzeitstag – Aufnahme 069",
    "width": 1333,
    "height": 2000,
    "chapter": "Schloss Bückeburg",
    "layout": "portrait"
  },
  {
    "id": "archive-070-img-7324",
    "src": "/media/archive/070-img-7324.webp",
    "alt": "Ein Blick auf die besondere Kulisse von Schloss Bückeburg – Aufnahme 070",
    "width": 2000,
    "height": 1333,
    "chapter": "Schloss Bückeburg",
    "layout": "quiet"
  },
  {
    "id": "archive-071-img-7327",
    "src": "/media/archive/071-img-7327.webp",
    "alt": "Architektur und Schlossgarten rund um die Trauung von Lea und Christoph – Aufnahme 071",
    "width": 2000,
    "height": 1333,
    "chapter": "Schloss Bückeburg",
    "layout": "standard"
  },
  {
    "id": "archive-088-img-7348",
    "src": "/media/archive/088-img-7348.webp",
    "alt": "Ein Blick auf die besondere Kulisse von Schloss Bückeburg – Aufnahme 088",
    "width": 2000,
    "height": 1333,
    "chapter": "Schloss Bückeburg",
    "layout": "quiet"
  },
  {
    "id": "archive-036-img-7243",
    "src": "/media/archive/036-img-7243.webp",
    "alt": "Lea und Christoph während ihrer standesamtlichen Trauung – Aufnahme 036",
    "width": 2000,
    "height": 1333,
    "chapter": "Unser Ja-Wort",
    "layout": "standard"
  },
  {
    "id": "archive-039-img-7250",
    "src": "/media/archive/039-img-7250.webp",
    "alt": "Lea und Christoph während ihrer standesamtlichen Trauung – Aufnahme 039",
    "width": 2000,
    "height": 1333,
    "chapter": "Unser Ja-Wort",
    "layout": "standard"
  },
  {
    "id": "archive-067-img-7318",
    "src": "/media/archive/067-img-7318.webp",
    "alt": "Ein Moment im historischen Trauzimmer von Schloss Bückeburg – Aufnahme 067",
    "width": 1264,
    "height": 2000,
    "chapter": "Unser Ja-Wort",
    "layout": "portrait"
  },
  {
    "id": "archive-068-img-7322",
    "src": "/media/archive/068-img-7322.webp",
    "alt": "Familie und Freunde begleiten Lea und Christoph bei ihrem Ja-Wort – Aufnahme 068",
    "width": 2000,
    "height": 1333,
    "chapter": "Unser Ja-Wort",
    "layout": "standard"
  },
  {
    "id": "archive-072-img-7328",
    "src": "/media/archive/072-img-7328.webp",
    "alt": "Lea und Christoph während ihrer standesamtlichen Trauung – Aufnahme 072",
    "width": 2000,
    "height": 1333,
    "chapter": "Unser Ja-Wort",
    "layout": "standard"
  },
  {
    "id": "archive-073-img-7329",
    "src": "/media/archive/073-img-7329.webp",
    "alt": "Ein Moment im historischen Trauzimmer von Schloss Bückeburg – Aufnahme 073",
    "width": 1333,
    "height": 2000,
    "chapter": "Unser Ja-Wort",
    "layout": "portrait"
  },
  {
    "id": "archive-074-img-7330",
    "src": "/media/archive/074-img-7330.webp",
    "alt": "Familie und Freunde begleiten Lea und Christoph bei ihrem Ja-Wort – Aufnahme 074",
    "width": 2000,
    "height": 1333,
    "chapter": "Unser Ja-Wort",
    "layout": "standard"
  },
  {
    "id": "archive-075-img-7331",
    "src": "/media/archive/075-img-7331.webp",
    "alt": "Lea und Christoph während ihrer standesamtlichen Trauung – Aufnahme 075",
    "width": 2000,
    "height": 1333,
    "chapter": "Unser Ja-Wort",
    "layout": "standard"
  },
  {
    "id": "archive-076-img-7332",
    "src": "/media/archive/076-img-7332.webp",
    "alt": "Ein Moment im historischen Trauzimmer von Schloss Bückeburg – Aufnahme 076",
    "width": 2000,
    "height": 1333,
    "chapter": "Unser Ja-Wort",
    "layout": "standard"
  },
  {
    "id": "archive-077-img-7333",
    "src": "/media/archive/077-img-7333.webp",
    "alt": "Familie und Freunde begleiten Lea und Christoph bei ihrem Ja-Wort – Aufnahme 077",
    "width": 1333,
    "height": 2000,
    "chapter": "Unser Ja-Wort",
    "layout": "portrait"
  },
  {
    "id": "archive-078-img-7334",
    "src": "/media/archive/078-img-7334.webp",
    "alt": "Lea und Christoph während ihrer standesamtlichen Trauung – Aufnahme 078",
    "width": 2000,
    "height": 1333,
    "chapter": "Unser Ja-Wort",
    "layout": "standard"
  },
  {
    "id": "archive-079-img-7335",
    "src": "/media/archive/079-img-7335.webp",
    "alt": "Ein Moment im historischen Trauzimmer von Schloss Bückeburg – Aufnahme 079",
    "width": 1333,
    "height": 2000,
    "chapter": "Unser Ja-Wort",
    "layout": "portrait"
  },
  {
    "id": "archive-080-img-7337",
    "src": "/media/archive/080-img-7337.webp",
    "alt": "Familie und Freunde begleiten Lea und Christoph bei ihrem Ja-Wort – Aufnahme 080",
    "width": 2000,
    "height": 1333,
    "chapter": "Unser Ja-Wort",
    "layout": "standard"
  },
  {
    "id": "archive-081-img-7338",
    "src": "/media/archive/081-img-7338.webp",
    "alt": "Lea und Christoph während ihrer standesamtlichen Trauung – Aufnahme 081",
    "width": 2000,
    "height": 1333,
    "chapter": "Unser Ja-Wort",
    "layout": "wide"
  },
  {
    "id": "archive-082-img-7339",
    "src": "/media/archive/082-img-7339.webp",
    "alt": "Ein Moment im historischen Trauzimmer von Schloss Bückeburg – Aufnahme 082",
    "width": 2000,
    "height": 1140,
    "chapter": "Unser Ja-Wort",
    "layout": "full"
  },
  {
    "id": "archive-083-img-7340",
    "src": "/media/archive/083-img-7340.webp",
    "alt": "Familie und Freunde begleiten Lea und Christoph bei ihrem Ja-Wort – Aufnahme 083",
    "width": 1333,
    "height": 2000,
    "chapter": "Unser Ja-Wort",
    "layout": "portrait"
  },
  {
    "id": "archive-084-img-7341",
    "src": "/media/archive/084-img-7341.webp",
    "alt": "Lea und Christoph während ihrer standesamtlichen Trauung – Aufnahme 084",
    "width": 2000,
    "height": 1333,
    "chapter": "Unser Ja-Wort",
    "layout": "standard"
  },
  {
    "id": "archive-085-img-7342",
    "src": "/media/archive/085-img-7342.webp",
    "alt": "Ein Moment im historischen Trauzimmer von Schloss Bückeburg – Aufnahme 085",
    "width": 2000,
    "height": 1333,
    "chapter": "Unser Ja-Wort",
    "layout": "wide"
  },
  {
    "id": "archive-086-img-7344",
    "src": "/media/archive/086-img-7344.webp",
    "alt": "Familie und Freunde begleiten Lea und Christoph bei ihrem Ja-Wort – Aufnahme 086",
    "width": 2000,
    "height": 1333,
    "chapter": "Unser Ja-Wort",
    "layout": "standard"
  },
  {
    "id": "archive-087-img-7345",
    "src": "/media/archive/087-img-7345.webp",
    "alt": "Lea und Christoph während ihrer standesamtlichen Trauung – Aufnahme 087",
    "width": 2000,
    "height": 1333,
    "chapter": "Unser Ja-Wort",
    "layout": "standard"
  },
  {
    "id": "archive-089-img-7350",
    "src": "/media/archive/089-img-7350.webp",
    "alt": "Familie und Freunde begleiten Lea und Christoph bei ihrem Ja-Wort – Aufnahme 089",
    "width": 1333,
    "height": 2000,
    "chapter": "Unser Ja-Wort",
    "layout": "portrait"
  },
  {
    "id": "archive-090-img-7351",
    "src": "/media/archive/090-img-7351.webp",
    "alt": "Lea und Christoph während ihrer standesamtlichen Trauung – Aufnahme 090",
    "width": 2000,
    "height": 1333,
    "chapter": "Unser Ja-Wort",
    "layout": "standard"
  },
  {
    "id": "archive-091-img-7352",
    "src": "/media/archive/091-img-7352.webp",
    "alt": "Ein Moment im historischen Trauzimmer von Schloss Bückeburg – Aufnahme 091",
    "width": 1333,
    "height": 2000,
    "chapter": "Unser Ja-Wort",
    "layout": "portrait"
  },
  {
    "id": "archive-092-img-7355",
    "src": "/media/archive/092-img-7355.webp",
    "alt": "Familie und Freunde begleiten Lea und Christoph bei ihrem Ja-Wort – Aufnahme 092",
    "width": 2000,
    "height": 1333,
    "chapter": "Unser Ja-Wort",
    "layout": "standard"
  },
  {
    "id": "archive-093-img-7356",
    "src": "/media/archive/093-img-7356.webp",
    "alt": "Lea und Christoph während ihrer standesamtlichen Trauung – Aufnahme 093",
    "width": 2000,
    "height": 1333,
    "chapter": "Unser Ja-Wort",
    "layout": "wide"
  },
  {
    "id": "archive-094-img-7360",
    "src": "/media/archive/094-img-7360.webp",
    "alt": "Ein Moment im historischen Trauzimmer von Schloss Bückeburg – Aufnahme 094",
    "width": 2000,
    "height": 1333,
    "chapter": "Unser Ja-Wort",
    "layout": "standard"
  },
  {
    "id": "archive-095-img-7361",
    "src": "/media/archive/095-img-7361.webp",
    "alt": "Familie und Freunde begleiten Lea und Christoph bei ihrem Ja-Wort – Aufnahme 095",
    "width": 2000,
    "height": 1185,
    "chapter": "Unser Ja-Wort",
    "layout": "standard"
  },
  {
    "id": "archive-096-img-7364",
    "src": "/media/archive/096-img-7364.webp",
    "alt": "Lea und Christoph während ihrer standesamtlichen Trauung – Aufnahme 096",
    "width": 2000,
    "height": 1333,
    "chapter": "Unser Ja-Wort",
    "layout": "standard"
  },
  {
    "id": "archive-097-img-7367",
    "src": "/media/archive/097-img-7367.webp",
    "alt": "Ein Moment im historischen Trauzimmer von Schloss Bückeburg – Aufnahme 097",
    "width": 1316,
    "height": 2000,
    "chapter": "Unser Ja-Wort",
    "layout": "portrait"
  },
  {
    "id": "archive-098-img-7370",
    "src": "/media/archive/098-img-7370.webp",
    "alt": "Familie und Freunde begleiten Lea und Christoph bei ihrem Ja-Wort – Aufnahme 098",
    "width": 2000,
    "height": 1333,
    "chapter": "Unser Ja-Wort",
    "layout": "standard"
  },
  {
    "id": "archive-099-img-7371",
    "src": "/media/archive/099-img-7371.webp",
    "alt": "Lea und Christoph während ihrer standesamtlichen Trauung – Aufnahme 099",
    "width": 2000,
    "height": 1333,
    "chapter": "Unser Ja-Wort",
    "layout": "standard"
  },
  {
    "id": "archive-100-img-7372",
    "src": "/media/archive/100-img-7372.webp",
    "alt": "Ein Moment im historischen Trauzimmer von Schloss Bückeburg – Aufnahme 100",
    "width": 2000,
    "height": 1333,
    "chapter": "Unser Ja-Wort",
    "layout": "standard"
  },
  {
    "id": "archive-101-img-7373",
    "src": "/media/archive/101-img-7373.webp",
    "alt": "Familie und Freunde begleiten Lea und Christoph bei ihrem Ja-Wort – Aufnahme 101",
    "width": 2000,
    "height": 1333,
    "chapter": "Unser Ja-Wort",
    "layout": "full"
  },
  {
    "id": "archive-102-img-7374",
    "src": "/media/archive/102-img-7374.webp",
    "alt": "Lea und Christoph während ihrer standesamtlichen Trauung – Aufnahme 102",
    "width": 2000,
    "height": 1333,
    "chapter": "Unser Ja-Wort",
    "layout": "standard"
  },
  {
    "id": "archive-103-img-7375",
    "src": "/media/archive/103-img-7375.webp",
    "alt": "Lea und Christoph nach ihrem Ja-Wort im Trauzimmer – Aufnahme 103",
    "width": 2000,
    "height": 1333,
    "chapter": "Das Versprechen",
    "layout": "standard"
  },
  {
    "id": "archive-104-img-7377",
    "src": "/media/archive/104-img-7377.webp",
    "alt": "Ein festgehaltener Moment voller Freude im Schloss – Aufnahme 104",
    "width": 2000,
    "height": 1333,
    "chapter": "Das Versprechen",
    "layout": "standard"
  },
  {
    "id": "archive-105-img-7382",
    "src": "/media/archive/105-img-7382.webp",
    "alt": "Ein emotionaler Augenblick während der Trauung von Lea und Christoph – Aufnahme 105",
    "width": 2000,
    "height": 1333,
    "chapter": "Das Versprechen",
    "layout": "wide"
  },
  {
    "id": "archive-106-img-7383",
    "src": "/media/archive/106-img-7383.webp",
    "alt": "Lea und Christoph nach ihrem Ja-Wort im Trauzimmer – Aufnahme 106",
    "width": 2000,
    "height": 1333,
    "chapter": "Das Versprechen",
    "layout": "quiet"
  },
  {
    "id": "archive-107-img-7385",
    "src": "/media/archive/107-img-7385.webp",
    "alt": "Ein festgehaltener Moment voller Freude im Schloss – Aufnahme 107",
    "width": 2000,
    "height": 1333,
    "chapter": "Das Versprechen",
    "layout": "standard"
  },
  {
    "id": "archive-108-img-7387",
    "src": "/media/archive/108-img-7387.webp",
    "alt": "Ein emotionaler Augenblick während der Trauung von Lea und Christoph – Aufnahme 108",
    "width": 2000,
    "height": 1333,
    "chapter": "Das Versprechen",
    "layout": "standard"
  },
  {
    "id": "archive-109-img-7391",
    "src": "/media/archive/109-img-7391.webp",
    "alt": "Lea und Christoph nach ihrem Ja-Wort im Trauzimmer – Aufnahme 109",
    "width": 1333,
    "height": 2000,
    "chapter": "Das Versprechen",
    "layout": "portrait"
  },
  {
    "id": "archive-110-img-7392",
    "src": "/media/archive/110-img-7392.webp",
    "alt": "Ein festgehaltener Moment voller Freude im Schloss – Aufnahme 110",
    "width": 1333,
    "height": 2000,
    "chapter": "Das Versprechen",
    "layout": "portrait"
  },
  {
    "id": "archive-111-img-7393",
    "src": "/media/archive/111-img-7393.webp",
    "alt": "Ein emotionaler Augenblick während der Trauung von Lea und Christoph – Aufnahme 111",
    "width": 2000,
    "height": 1333,
    "chapter": "Das Versprechen",
    "layout": "standard"
  },
  {
    "id": "archive-112-img-7398",
    "src": "/media/archive/112-img-7398.webp",
    "alt": "Lea und Christoph nach ihrem Ja-Wort im Trauzimmer – Aufnahme 112",
    "width": 2000,
    "height": 1333,
    "chapter": "Das Versprechen",
    "layout": "standard"
  },
  {
    "id": "archive-113-img-7401",
    "src": "/media/archive/113-img-7401.webp",
    "alt": "Ein festgehaltener Moment voller Freude im Schloss – Aufnahme 113",
    "width": 1333,
    "height": 2000,
    "chapter": "Das Versprechen",
    "layout": "portrait"
  },
  {
    "id": "archive-114-img-7405",
    "src": "/media/archive/114-img-7405.webp",
    "alt": "Ein emotionaler Augenblick während der Trauung von Lea und Christoph – Aufnahme 114",
    "width": 2000,
    "height": 1333,
    "chapter": "Das Versprechen",
    "layout": "standard"
  },
  {
    "id": "archive-115-img-7406",
    "src": "/media/archive/115-img-7406.webp",
    "alt": "Lea und Christoph nach ihrem Ja-Wort im Trauzimmer – Aufnahme 115",
    "width": 2000,
    "height": 1380,
    "chapter": "Das Versprechen",
    "layout": "quiet"
  },
  {
    "id": "archive-116-img-7407",
    "src": "/media/archive/116-img-7407.webp",
    "alt": "Ein festgehaltener Moment voller Freude im Schloss – Aufnahme 116",
    "width": 2000,
    "height": 1501,
    "chapter": "Das Versprechen",
    "layout": "standard"
  },
  {
    "id": "archive-117-img-7413",
    "src": "/media/archive/117-img-7413.webp",
    "alt": "Ein emotionaler Augenblick während der Trauung von Lea und Christoph – Aufnahme 117",
    "width": 2000,
    "height": 1333,
    "chapter": "Das Versprechen",
    "layout": "wide"
  },
  {
    "id": "archive-118-img-7415",
    "src": "/media/archive/118-img-7415.webp",
    "alt": "Lea und Christoph nach ihrem Ja-Wort im Trauzimmer – Aufnahme 118",
    "width": 2000,
    "height": 1333,
    "chapter": "Das Versprechen",
    "layout": "standard"
  },
  {
    "id": "archive-119-img-7419",
    "src": "/media/archive/119-img-7419.webp",
    "alt": "Ein festgehaltener Moment voller Freude im Schloss – Aufnahme 119",
    "width": 2000,
    "height": 1333,
    "chapter": "Das Versprechen",
    "layout": "standard"
  },
  {
    "id": "archive-120-img-7420",
    "src": "/media/archive/120-img-7420.webp",
    "alt": "Ein emotionaler Augenblick während der Trauung von Lea und Christoph – Aufnahme 120",
    "width": 2000,
    "height": 1333,
    "chapter": "Das Versprechen",
    "layout": "full"
  },
  {
    "id": "archive-121-img-7421",
    "src": "/media/archive/121-img-7421.webp",
    "alt": "Lea und Christoph nach ihrem Ja-Wort im Trauzimmer – Aufnahme 121",
    "width": 2000,
    "height": 1333,
    "chapter": "Das Versprechen",
    "layout": "wide"
  },
  {
    "id": "archive-122-img-7422",
    "src": "/media/archive/122-img-7422.webp",
    "alt": "Ein festgehaltener Moment voller Freude im Schloss – Aufnahme 122",
    "width": 2000,
    "height": 1333,
    "chapter": "Das Versprechen",
    "layout": "standard"
  },
  {
    "id": "archive-123-img-7423",
    "src": "/media/archive/123-img-7423.webp",
    "alt": "Ein emotionaler Augenblick während der Trauung von Lea und Christoph – Aufnahme 123",
    "width": 2000,
    "height": 1333,
    "chapter": "Das Versprechen",
    "layout": "standard"
  },
  {
    "id": "archive-124-img-7424",
    "src": "/media/archive/124-img-7424.webp",
    "alt": "Lea und Christoph nach ihrem Ja-Wort im Trauzimmer – Aufnahme 124",
    "width": 2000,
    "height": 1333,
    "chapter": "Das Versprechen",
    "layout": "quiet"
  },
  {
    "id": "archive-125-img-7427",
    "src": "/media/archive/125-img-7427.webp",
    "alt": "Ein festgehaltener Moment voller Freude im Schloss – Aufnahme 125",
    "width": 2000,
    "height": 1333,
    "chapter": "Das Versprechen",
    "layout": "wide"
  },
  {
    "id": "archive-126-img-7431-3",
    "src": "/media/archive/126-img-7431-3.webp",
    "alt": "Ein emotionaler Augenblick während der Trauung von Lea und Christoph – Aufnahme 126",
    "width": 2000,
    "height": 1333,
    "chapter": "Das Versprechen",
    "layout": "standard"
  },
  {
    "id": "archive-127-img-7433",
    "src": "/media/archive/127-img-7433.webp",
    "alt": "Lea und Christoph nach ihrem Ja-Wort im Trauzimmer – Aufnahme 127",
    "width": 2000,
    "height": 1333,
    "chapter": "Das Versprechen",
    "layout": "standard"
  },
  {
    "id": "archive-128-img-7434",
    "src": "/media/archive/128-img-7434.webp",
    "alt": "Ein festgehaltener Moment voller Freude im Schloss – Aufnahme 128",
    "width": 2000,
    "height": 1333,
    "chapter": "Das Versprechen",
    "layout": "standard"
  },
  {
    "id": "archive-129-img-7436",
    "src": "/media/archive/129-img-7436.webp",
    "alt": "Ein emotionaler Augenblick während der Trauung von Lea und Christoph – Aufnahme 129",
    "width": 2000,
    "height": 1333,
    "chapter": "Das Versprechen",
    "layout": "wide"
  },
  {
    "id": "archive-130-img-7437",
    "src": "/media/archive/130-img-7437.webp",
    "alt": "Lea und Christoph nach ihrem Ja-Wort im Trauzimmer – Aufnahme 130",
    "width": 1333,
    "height": 2000,
    "chapter": "Das Versprechen",
    "layout": "portrait"
  },
  {
    "id": "archive-131-img-7439",
    "src": "/media/archive/131-img-7439.webp",
    "alt": "Ein festgehaltener Moment voller Freude im Schloss – Aufnahme 131",
    "width": 2000,
    "height": 1333,
    "chapter": "Das Versprechen",
    "layout": "standard"
  },
  {
    "id": "archive-132-img-7440",
    "src": "/media/archive/132-img-7440.webp",
    "alt": "Ein emotionaler Augenblick während der Trauung von Lea und Christoph – Aufnahme 132",
    "width": 2000,
    "height": 1333,
    "chapter": "Das Versprechen",
    "layout": "standard"
  },
  {
    "id": "archive-133-img-7441-3",
    "src": "/media/archive/133-img-7441-3.webp",
    "alt": "Lea und Christoph nach ihrem Ja-Wort im Trauzimmer – Aufnahme 133",
    "width": 2000,
    "height": 1333,
    "chapter": "Das Versprechen",
    "layout": "quiet"
  },
  {
    "id": "archive-134-img-7443",
    "src": "/media/archive/134-img-7443.webp",
    "alt": "Ein festgehaltener Moment voller Freude im Schloss – Aufnahme 134",
    "width": 2000,
    "height": 1333,
    "chapter": "Das Versprechen",
    "layout": "standard"
  },
  {
    "id": "archive-135-img-7445",
    "src": "/media/archive/135-img-7445.webp",
    "alt": "Ein emotionaler Augenblick während der Trauung von Lea und Christoph – Aufnahme 135",
    "width": 1333,
    "height": 2000,
    "chapter": "Das Versprechen",
    "layout": "portrait"
  },
  {
    "id": "archive-136-img-7446",
    "src": "/media/archive/136-img-7446.webp",
    "alt": "Lea und Christoph nach ihrem Ja-Wort im Trauzimmer – Aufnahme 136",
    "width": 1333,
    "height": 2000,
    "chapter": "Das Versprechen",
    "layout": "portrait"
  },
  {
    "id": "archive-137-img-7450",
    "src": "/media/archive/137-img-7450.webp",
    "alt": "Familie und Freunde teilen die Freude des Brautpaares – Aufnahme 137",
    "width": 2000,
    "height": 1333,
    "chapter": "Freude vor dem Schloss",
    "layout": "wide"
  },
  {
    "id": "archive-138-img-7451",
    "src": "/media/archive/138-img-7451.webp",
    "alt": "Lea und Christoph feiern vor dem Schloss mit ihren Gästen – Aufnahme 138",
    "width": 2000,
    "height": 1333,
    "chapter": "Freude vor dem Schloss",
    "layout": "standard"
  },
  {
    "id": "archive-139-img-7452",
    "src": "/media/archive/139-img-7452.webp",
    "alt": "Glückwünsche, Umarmungen und Lachen nach der Trauung – Aufnahme 139",
    "width": 2000,
    "height": 1333,
    "chapter": "Freude vor dem Schloss",
    "layout": "full"
  },
  {
    "id": "archive-140-img-7453",
    "src": "/media/archive/140-img-7453.webp",
    "alt": "Familie und Freunde teilen die Freude des Brautpaares – Aufnahme 140",
    "width": 2000,
    "height": 1333,
    "chapter": "Freude vor dem Schloss",
    "layout": "standard"
  },
  {
    "id": "archive-141-img-7455",
    "src": "/media/archive/141-img-7455.webp",
    "alt": "Lea und Christoph feiern vor dem Schloss mit ihren Gästen – Aufnahme 141",
    "width": 2000,
    "height": 1333,
    "chapter": "Freude vor dem Schloss",
    "layout": "wide"
  },
  {
    "id": "archive-142-img-7457",
    "src": "/media/archive/142-img-7457.webp",
    "alt": "Glückwünsche, Umarmungen und Lachen nach der Trauung – Aufnahme 142",
    "width": 1403,
    "height": 2000,
    "chapter": "Freude vor dem Schloss",
    "layout": "portrait"
  },
  {
    "id": "archive-143-img-7460",
    "src": "/media/archive/143-img-7460.webp",
    "alt": "Familie und Freunde teilen die Freude des Brautpaares – Aufnahme 143",
    "width": 1333,
    "height": 2000,
    "chapter": "Freude vor dem Schloss",
    "layout": "portrait"
  },
  {
    "id": "archive-144-img-7462",
    "src": "/media/archive/144-img-7462.webp",
    "alt": "Lea und Christoph feiern vor dem Schloss mit ihren Gästen – Aufnahme 144",
    "width": 1333,
    "height": 2000,
    "chapter": "Freude vor dem Schloss",
    "layout": "portrait"
  },
  {
    "id": "archive-145-img-7463",
    "src": "/media/archive/145-img-7463.webp",
    "alt": "Glückwünsche, Umarmungen und Lachen nach der Trauung – Aufnahme 145",
    "width": 2000,
    "height": 1333,
    "chapter": "Freude vor dem Schloss",
    "layout": "wide"
  },
  {
    "id": "archive-146-img-7465",
    "src": "/media/archive/146-img-7465.webp",
    "alt": "Familie und Freunde teilen die Freude des Brautpaares – Aufnahme 146",
    "width": 2000,
    "height": 1333,
    "chapter": "Freude vor dem Schloss",
    "layout": "standard"
  },
  {
    "id": "archive-147-img-7468",
    "src": "/media/archive/147-img-7468.webp",
    "alt": "Lea und Christoph feiern vor dem Schloss mit ihren Gästen – Aufnahme 147",
    "width": 2000,
    "height": 1333,
    "chapter": "Freude vor dem Schloss",
    "layout": "standard"
  },
  {
    "id": "archive-148-img-7469",
    "src": "/media/archive/148-img-7469.webp",
    "alt": "Glückwünsche, Umarmungen und Lachen nach der Trauung – Aufnahme 148",
    "width": 2000,
    "height": 1333,
    "chapter": "Freude vor dem Schloss",
    "layout": "standard"
  },
  {
    "id": "archive-149-img-7472",
    "src": "/media/archive/149-img-7472.webp",
    "alt": "Familie und Freunde teilen die Freude des Brautpaares – Aufnahme 149",
    "width": 2000,
    "height": 1333,
    "chapter": "Freude vor dem Schloss",
    "layout": "wide"
  },
  {
    "id": "archive-150-img-7476",
    "src": "/media/archive/150-img-7476.webp",
    "alt": "Lea und Christoph feiern vor dem Schloss mit ihren Gästen – Aufnahme 150",
    "width": 1333,
    "height": 2000,
    "chapter": "Freude vor dem Schloss",
    "layout": "portrait"
  },
  {
    "id": "archive-151-img-7477",
    "src": "/media/archive/151-img-7477.webp",
    "alt": "Glückwünsche, Umarmungen und Lachen nach der Trauung – Aufnahme 151",
    "width": 1333,
    "height": 2000,
    "chapter": "Freude vor dem Schloss",
    "layout": "portrait"
  },
  {
    "id": "archive-152-img-7479",
    "src": "/media/archive/152-img-7479.webp",
    "alt": "Familie und Freunde teilen die Freude des Brautpaares – Aufnahme 152",
    "width": 2000,
    "height": 1333,
    "chapter": "Freude vor dem Schloss",
    "layout": "standard"
  },
  {
    "id": "archive-153-img-7483",
    "src": "/media/archive/153-img-7483.webp",
    "alt": "Lea und Christoph feiern vor dem Schloss mit ihren Gästen – Aufnahme 153",
    "width": 2000,
    "height": 1333,
    "chapter": "Freude vor dem Schloss",
    "layout": "wide"
  },
  {
    "id": "archive-154-img-7484",
    "src": "/media/archive/154-img-7484.webp",
    "alt": "Glückwünsche, Umarmungen und Lachen nach der Trauung – Aufnahme 154",
    "width": 2000,
    "height": 1333,
    "chapter": "Freude vor dem Schloss",
    "layout": "standard"
  },
  {
    "id": "archive-155-img-7485",
    "src": "/media/archive/155-img-7485.webp",
    "alt": "Familie und Freunde teilen die Freude des Brautpaares – Aufnahme 155",
    "width": 2000,
    "height": 1333,
    "chapter": "Freude vor dem Schloss",
    "layout": "standard"
  },
  {
    "id": "archive-156-img-7489",
    "src": "/media/archive/156-img-7489.webp",
    "alt": "Lea und Christoph feiern vor dem Schloss mit ihren Gästen – Aufnahme 156",
    "width": 2000,
    "height": 1333,
    "chapter": "Freude vor dem Schloss",
    "layout": "standard"
  },
  {
    "id": "archive-157-img-7490",
    "src": "/media/archive/157-img-7490.webp",
    "alt": "Glückwünsche, Umarmungen und Lachen nach der Trauung – Aufnahme 157",
    "width": 2000,
    "height": 1333,
    "chapter": "Freude vor dem Schloss",
    "layout": "wide"
  },
  {
    "id": "archive-158-img-7493",
    "src": "/media/archive/158-img-7493.webp",
    "alt": "Familie und Freunde teilen die Freude des Brautpaares – Aufnahme 158",
    "width": 1333,
    "height": 2000,
    "chapter": "Freude vor dem Schloss",
    "layout": "full"
  },
  {
    "id": "archive-159-img-7494",
    "src": "/media/archive/159-img-7494.webp",
    "alt": "Lea und Christoph feiern vor dem Schloss mit ihren Gästen – Aufnahme 159",
    "width": 2000,
    "height": 1333,
    "chapter": "Freude vor dem Schloss",
    "layout": "standard"
  },
  {
    "id": "archive-160-img-7495",
    "src": "/media/archive/160-img-7495.webp",
    "alt": "Glückwünsche, Umarmungen und Lachen nach der Trauung – Aufnahme 160",
    "width": 2000,
    "height": 1333,
    "chapter": "Freude vor dem Schloss",
    "layout": "quiet"
  },
  {
    "id": "archive-161-img-7496",
    "src": "/media/archive/161-img-7496.webp",
    "alt": "Familie und Freunde teilen die Freude des Brautpaares – Aufnahme 161",
    "width": 2000,
    "height": 1333,
    "chapter": "Freude vor dem Schloss",
    "layout": "wide"
  },
  {
    "id": "archive-162-img-7498",
    "src": "/media/archive/162-img-7498.webp",
    "alt": "Lea und Christoph feiern vor dem Schloss mit ihren Gästen – Aufnahme 162",
    "width": 2000,
    "height": 1333,
    "chapter": "Freude vor dem Schloss",
    "layout": "standard"
  },
  {
    "id": "archive-163-img-7499",
    "src": "/media/archive/163-img-7499.webp",
    "alt": "Glückwünsche, Umarmungen und Lachen nach der Trauung – Aufnahme 163",
    "width": 2000,
    "height": 1333,
    "chapter": "Freude vor dem Schloss",
    "layout": "standard"
  },
  {
    "id": "archive-164-img-7501",
    "src": "/media/archive/164-img-7501.webp",
    "alt": "Familie und Freunde teilen die Freude des Brautpaares – Aufnahme 164",
    "width": 1333,
    "height": 2000,
    "chapter": "Freude vor dem Schloss",
    "layout": "portrait"
  },
  {
    "id": "archive-165-img-7502",
    "src": "/media/archive/165-img-7502.webp",
    "alt": "Lea und Christoph feiern vor dem Schloss mit ihren Gästen – Aufnahme 165",
    "width": 2000,
    "height": 1333,
    "chapter": "Freude vor dem Schloss",
    "layout": "wide"
  },
  {
    "id": "archive-166-img-7503",
    "src": "/media/archive/166-img-7503.webp",
    "alt": "Glückwünsche, Umarmungen und Lachen nach der Trauung – Aufnahme 166",
    "width": 2000,
    "height": 1195,
    "chapter": "Freude vor dem Schloss",
    "layout": "standard"
  },
  {
    "id": "archive-167-img-7506",
    "src": "/media/archive/167-img-7506.webp",
    "alt": "Familie und Freunde teilen die Freude des Brautpaares – Aufnahme 167",
    "width": 1333,
    "height": 2000,
    "chapter": "Freude vor dem Schloss",
    "layout": "portrait"
  },
  {
    "id": "archive-168-img-7507",
    "src": "/media/archive/168-img-7507.webp",
    "alt": "Lea und Christoph feiern vor dem Schloss mit ihren Gästen – Aufnahme 168",
    "width": 2000,
    "height": 1333,
    "chapter": "Freude vor dem Schloss",
    "layout": "standard"
  },
  {
    "id": "archive-169-img-7509",
    "src": "/media/archive/169-img-7509.webp",
    "alt": "Glückwünsche, Umarmungen und Lachen nach der Trauung – Aufnahme 169",
    "width": 2000,
    "height": 1333,
    "chapter": "Freude vor dem Schloss",
    "layout": "quiet"
  },
  {
    "id": "archive-170-img-7511",
    "src": "/media/archive/170-img-7511.webp",
    "alt": "Familie und Freunde teilen die Freude des Brautpaares – Aufnahme 170",
    "width": 2000,
    "height": 1333,
    "chapter": "Freude vor dem Schloss",
    "layout": "standard"
  },
  {
    "id": "archive-171-img-7523",
    "src": "/media/archive/171-img-7523.webp",
    "alt": "Lea und Christoph feiern vor dem Schloss mit ihren Gästen – Aufnahme 171",
    "width": 2000,
    "height": 1333,
    "chapter": "Freude vor dem Schloss",
    "layout": "standard"
  },
  {
    "id": "archive-028-img-7179",
    "src": "/media/archive/028-img-7179.webp",
    "alt": "Ein inniger Moment von Lea und Christoph nach der Trauung – Aufnahme 028",
    "width": 1333,
    "height": 2000,
    "chapter": "Endlich wir",
    "layout": "portrait"
  },
  {
    "id": "archive-029-img-7182",
    "src": "/media/archive/029-img-7182.webp",
    "alt": "Das Brautpaar vor der historischen Kulisse des Schlosses – Aufnahme 029",
    "width": 1333,
    "height": 2000,
    "chapter": "Endlich wir",
    "layout": "portrait"
  },
  {
    "id": "archive-030-img-7184-3",
    "src": "/media/archive/030-img-7184-3.webp",
    "alt": "Lea und Christoph bei ihren Hochzeitsportraits im Schloss Bückeburg – Aufnahme 030",
    "width": 1333,
    "height": 2000,
    "chapter": "Endlich wir",
    "layout": "portrait"
  },
  {
    "id": "archive-031-img-7187",
    "src": "/media/archive/031-img-7187.webp",
    "alt": "Ein inniger Moment von Lea und Christoph nach der Trauung – Aufnahme 031",
    "width": 2000,
    "height": 1333,
    "chapter": "Endlich wir",
    "layout": "standard"
  },
  {
    "id": "archive-034-img-7238",
    "src": "/media/archive/034-img-7238.webp",
    "alt": "Ein inniger Moment von Lea und Christoph nach der Trauung – Aufnahme 034",
    "width": 1333,
    "height": 2000,
    "chapter": "Endlich wir",
    "layout": "portrait"
  },
  {
    "id": "archive-037-img-7244",
    "src": "/media/archive/037-img-7244.webp",
    "alt": "Ein inniger Moment von Lea und Christoph nach der Trauung – Aufnahme 037",
    "width": 2000,
    "height": 1333,
    "chapter": "Endlich wir",
    "layout": "wide"
  },
  {
    "id": "archive-038-img-7246",
    "src": "/media/archive/038-img-7246.webp",
    "alt": "Das Brautpaar vor der historischen Kulisse des Schlosses – Aufnahme 038",
    "width": 1333,
    "height": 2000,
    "chapter": "Endlich wir",
    "layout": "portrait"
  },
  {
    "id": "archive-041-img-7257",
    "src": "/media/archive/041-img-7257.webp",
    "alt": "Das Brautpaar vor der historischen Kulisse des Schlosses – Aufnahme 041",
    "width": 2000,
    "height": 1333,
    "chapter": "Endlich wir",
    "layout": "wide"
  },
  {
    "id": "archive-044-img-7270",
    "src": "/media/archive/044-img-7270.webp",
    "alt": "Das Brautpaar vor der historischen Kulisse des Schlosses – Aufnahme 044",
    "width": 2000,
    "height": 1499,
    "chapter": "Endlich wir",
    "layout": "full"
  },
  {
    "id": "archive-172-img-7537",
    "src": "/media/archive/172-img-7537.webp",
    "alt": "Ein inniger Moment von Lea und Christoph nach der Trauung – Aufnahme 172",
    "width": 2000,
    "height": 1333,
    "chapter": "Endlich wir",
    "layout": "standard"
  },
  {
    "id": "archive-173-img-7541",
    "src": "/media/archive/173-img-7541.webp",
    "alt": "Das Brautpaar vor der historischen Kulisse des Schlosses – Aufnahme 173",
    "width": 1333,
    "height": 2000,
    "chapter": "Endlich wir",
    "layout": "portrait"
  },
  {
    "id": "archive-174-img-7545",
    "src": "/media/archive/174-img-7545.webp",
    "alt": "Lea und Christoph bei ihren Hochzeitsportraits im Schloss Bückeburg – Aufnahme 174",
    "width": 2000,
    "height": 1334,
    "chapter": "Endlich wir",
    "layout": "standard"
  },
  {
    "id": "archive-175-img-7546",
    "src": "/media/archive/175-img-7546.webp",
    "alt": "Ein inniger Moment von Lea und Christoph nach der Trauung – Aufnahme 175",
    "width": 1333,
    "height": 2000,
    "chapter": "Endlich wir",
    "layout": "portrait"
  },
  {
    "id": "archive-176-img-7554",
    "src": "/media/archive/176-img-7554.webp",
    "alt": "Das Brautpaar vor der historischen Kulisse des Schlosses – Aufnahme 176",
    "width": 1333,
    "height": 2000,
    "chapter": "Endlich wir",
    "layout": "portrait"
  },
  {
    "id": "archive-177-img-7560",
    "src": "/media/archive/177-img-7560.webp",
    "alt": "Lea und Christoph bei ihren Hochzeitsportraits im Schloss Bückeburg – Aufnahme 177",
    "width": 1333,
    "height": 2000,
    "chapter": "Endlich wir",
    "layout": "full"
  },
  {
    "id": "archive-178-img-7577",
    "src": "/media/archive/178-img-7577.webp",
    "alt": "Ein inniger Moment von Lea und Christoph nach der Trauung – Aufnahme 178",
    "width": 1333,
    "height": 2000,
    "chapter": "Endlich wir",
    "layout": "portrait"
  },
  {
    "id": "archive-179-img-7579",
    "src": "/media/archive/179-img-7579.webp",
    "alt": "Das Brautpaar vor der historischen Kulisse des Schlosses – Aufnahme 179",
    "width": 1333,
    "height": 2000,
    "chapter": "Endlich wir",
    "layout": "portrait"
  },
  {
    "id": "archive-180-img-7583",
    "src": "/media/archive/180-img-7583.webp",
    "alt": "Lea und Christoph bei ihren Hochzeitsportraits im Schloss Bückeburg – Aufnahme 180",
    "width": 2000,
    "height": 1353,
    "chapter": "Endlich wir",
    "layout": "standard"
  },
  {
    "id": "archive-181-img-7585",
    "src": "/media/archive/181-img-7585.webp",
    "alt": "Ein inniger Moment von Lea und Christoph nach der Trauung – Aufnahme 181",
    "width": 1237,
    "height": 2000,
    "chapter": "Endlich wir",
    "layout": "portrait"
  },
  {
    "id": "archive-182-img-7586",
    "src": "/media/archive/182-img-7586.webp",
    "alt": "Das Brautpaar vor der historischen Kulisse des Schlosses – Aufnahme 182",
    "width": 1333,
    "height": 2000,
    "chapter": "Endlich wir",
    "layout": "portrait"
  },
  {
    "id": "archive-183-img-7601",
    "src": "/media/archive/183-img-7601.webp",
    "alt": "Lea und Christoph bei ihren Hochzeitsportraits im Schloss Bückeburg – Aufnahme 183",
    "width": 1333,
    "height": 2000,
    "chapter": "Endlich wir",
    "layout": "portrait"
  },
  {
    "id": "archive-184-img-7630",
    "src": "/media/archive/184-img-7630.webp",
    "alt": "Ein inniger Moment von Lea und Christoph nach der Trauung – Aufnahme 184",
    "width": 1333,
    "height": 2000,
    "chapter": "Endlich wir",
    "layout": "portrait"
  },
  {
    "id": "archive-185-img-7632",
    "src": "/media/archive/185-img-7632.webp",
    "alt": "Das Brautpaar vor der historischen Kulisse des Schlosses – Aufnahme 185",
    "width": 1333,
    "height": 2000,
    "chapter": "Endlich wir",
    "layout": "portrait"
  },
  {
    "id": "archive-025-img-7168",
    "src": "/media/archive/025-img-7168.webp",
    "alt": "Ein Gruppenportrait mit Menschen, die den Hochzeitstag begleitet haben – Aufnahme 025",
    "width": 2000,
    "height": 1154,
    "chapter": "Unsere Familien und Freunde",
    "layout": "full"
  },
  {
    "id": "archive-026-img-7170",
    "src": "/media/archive/026-img-7170.webp",
    "alt": "Familie, Freunde und das Brautpaar im Schlossgarten – Aufnahme 026",
    "width": 1333,
    "height": 2000,
    "chapter": "Unsere Familien und Freunde",
    "layout": "portrait"
  },
  {
    "id": "archive-027-img-7172",
    "src": "/media/archive/027-img-7172.webp",
    "alt": "Lea und Christoph gemeinsam mit Familie und Freunden – Aufnahme 027",
    "width": 2000,
    "height": 1333,
    "chapter": "Unsere Familien und Freunde",
    "layout": "standard"
  },
  {
    "id": "archive-032-img-7199",
    "src": "/media/archive/032-img-7199.webp",
    "alt": "Familie, Freunde und das Brautpaar im Schlossgarten – Aufnahme 032",
    "width": 2000,
    "height": 1333,
    "chapter": "Unsere Familien und Freunde",
    "layout": "standard"
  },
  {
    "id": "archive-033-img-7237",
    "src": "/media/archive/033-img-7237.webp",
    "alt": "Lea und Christoph gemeinsam mit Familie und Freunden – Aufnahme 033",
    "width": 2000,
    "height": 1333,
    "chapter": "Unsere Familien und Freunde",
    "layout": "wide"
  },
  {
    "id": "archive-035-img-7241",
    "src": "/media/archive/035-img-7241.webp",
    "alt": "Familie, Freunde und das Brautpaar im Schlossgarten – Aufnahme 035",
    "width": 2000,
    "height": 1333,
    "chapter": "Unsere Familien und Freunde",
    "layout": "standard"
  },
  {
    "id": "archive-040-img-7254",
    "src": "/media/archive/040-img-7254.webp",
    "alt": "Ein Gruppenportrait mit Menschen, die den Hochzeitstag begleitet haben – Aufnahme 040",
    "width": 2000,
    "height": 1304,
    "chapter": "Unsere Familien und Freunde",
    "layout": "standard"
  },
  {
    "id": "archive-042-img-7262",
    "src": "/media/archive/042-img-7262.webp",
    "alt": "Lea und Christoph gemeinsam mit Familie und Freunden – Aufnahme 042",
    "width": 2000,
    "height": 1290,
    "chapter": "Unsere Familien und Freunde",
    "layout": "standard"
  },
  {
    "id": "archive-043-img-7267",
    "src": "/media/archive/043-img-7267.webp",
    "alt": "Ein Gruppenportrait mit Menschen, die den Hochzeitstag begleitet haben – Aufnahme 043",
    "width": 1333,
    "height": 2000,
    "chapter": "Unsere Familien und Freunde",
    "layout": "portrait"
  },
  {
    "id": "archive-046-img-7279",
    "src": "/media/archive/046-img-7279.webp",
    "alt": "Ein Gruppenportrait mit Menschen, die den Hochzeitstag begleitet haben – Aufnahme 046",
    "width": 2000,
    "height": 1333,
    "chapter": "Unsere Familien und Freunde",
    "layout": "standard"
  },
  {
    "id": "archive-047-img-7283",
    "src": "/media/archive/047-img-7283.webp",
    "alt": "Familie, Freunde und das Brautpaar im Schlossgarten – Aufnahme 047",
    "width": 2000,
    "height": 1409,
    "chapter": "Unsere Familien und Freunde",
    "layout": "standard"
  },
  {
    "id": "archive-050-img-7286",
    "src": "/media/archive/050-img-7286.webp",
    "alt": "Familie, Freunde und das Brautpaar im Schlossgarten – Aufnahme 050",
    "width": 2000,
    "height": 1333,
    "chapter": "Unsere Familien und Freunde",
    "layout": "standard"
  },
  {
    "id": "archive-052-img-7289",
    "src": "/media/archive/052-img-7289.webp",
    "alt": "Ein Gruppenportrait mit Menschen, die den Hochzeitstag begleitet haben – Aufnahme 052",
    "width": 2000,
    "height": 1517,
    "chapter": "Unsere Familien und Freunde",
    "layout": "quiet"
  },
  {
    "id": "archive-053-img-7291",
    "src": "/media/archive/053-img-7291.webp",
    "alt": "Familie, Freunde und das Brautpaar im Schlossgarten – Aufnahme 053",
    "width": 2000,
    "height": 1333,
    "chapter": "Unsere Familien und Freunde",
    "layout": "wide"
  },
  {
    "id": "archive-055-img-7294",
    "src": "/media/archive/055-img-7294.webp",
    "alt": "Ein Gruppenportrait mit Menschen, die den Hochzeitstag begleitet haben – Aufnahme 055",
    "width": 1333,
    "height": 2000,
    "chapter": "Unsere Familien und Freunde",
    "layout": "portrait"
  },
  {
    "id": "archive-057-img-7299",
    "src": "/media/archive/057-img-7299.webp",
    "alt": "Lea und Christoph gemeinsam mit Familie und Freunden – Aufnahme 057",
    "width": 2000,
    "height": 1333,
    "chapter": "Unsere Familien und Freunde",
    "layout": "wide"
  },
  {
    "id": "archive-058-img-7300",
    "src": "/media/archive/058-img-7300.webp",
    "alt": "Ein Gruppenportrait mit Menschen, die den Hochzeitstag begleitet haben – Aufnahme 058",
    "width": 2000,
    "height": 1436,
    "chapter": "Unsere Familien und Freunde",
    "layout": "standard"
  },
  {
    "id": "archive-060-img-7304",
    "src": "/media/archive/060-img-7304.webp",
    "alt": "Lea und Christoph gemeinsam mit Familie und Freunden – Aufnahme 060",
    "width": 2000,
    "height": 1333,
    "chapter": "Unsere Familien und Freunde",
    "layout": "standard"
  },
  {
    "id": "archive-061-img-7305",
    "src": "/media/archive/061-img-7305.webp",
    "alt": "Ein Gruppenportrait mit Menschen, die den Hochzeitstag begleitet haben – Aufnahme 061",
    "width": 1333,
    "height": 2000,
    "chapter": "Unsere Familien und Freunde",
    "layout": "portrait"
  },
  {
    "id": "archive-062-img-7306",
    "src": "/media/archive/062-img-7306.webp",
    "alt": "Familie, Freunde und das Brautpaar im Schlossgarten – Aufnahme 062",
    "width": 2000,
    "height": 1262,
    "chapter": "Unsere Familien und Freunde",
    "layout": "standard"
  },
  {
    "id": "archive-063-img-7307",
    "src": "/media/archive/063-img-7307.webp",
    "alt": "Lea und Christoph gemeinsam mit Familie und Freunden – Aufnahme 063",
    "width": 1333,
    "height": 2000,
    "chapter": "Unsere Familien und Freunde",
    "layout": "full"
  },
  {
    "id": "archive-064-img-7310",
    "src": "/media/archive/064-img-7310.webp",
    "alt": "Ein Gruppenportrait mit Menschen, die den Hochzeitstag begleitet haben – Aufnahme 064",
    "width": 2000,
    "height": 1333,
    "chapter": "Unsere Familien und Freunde",
    "layout": "standard"
  },
  {
    "id": "archive-065-img-7311",
    "src": "/media/archive/065-img-7311.webp",
    "alt": "Familie, Freunde und das Brautpaar im Schlossgarten – Aufnahme 065",
    "width": 1333,
    "height": 2000,
    "chapter": "Unsere Familien und Freunde",
    "layout": "portrait"
  },
  {
    "id": "archive-186-img-7647",
    "src": "/media/archive/186-img-7647.webp",
    "alt": "Lea und Christoph gemeinsam mit Familie und Freunden – Aufnahme 186",
    "width": 2000,
    "height": 1333,
    "chapter": "Unsere Familien und Freunde",
    "layout": "standard"
  },
  {
    "id": "archive-187-img-7652",
    "src": "/media/archive/187-img-7652.webp",
    "alt": "Ein Gruppenportrait mit Menschen, die den Hochzeitstag begleitet haben – Aufnahme 187",
    "width": 1333,
    "height": 2000,
    "chapter": "Unsere Familien und Freunde",
    "layout": "portrait"
  },
  {
    "id": "archive-188-img-7653",
    "src": "/media/archive/188-img-7653.webp",
    "alt": "Familie, Freunde und das Brautpaar im Schlossgarten – Aufnahme 188",
    "width": 2000,
    "height": 1333,
    "chapter": "Unsere Familien und Freunde",
    "layout": "standard"
  },
  {
    "id": "archive-189-img-7656",
    "src": "/media/archive/189-img-7656.webp",
    "alt": "Lea und Christoph gemeinsam mit Familie und Freunden – Aufnahme 189",
    "width": 1237,
    "height": 2000,
    "chapter": "Unsere Familien und Freunde",
    "layout": "portrait"
  },
  {
    "id": "archive-190-img-7660",
    "src": "/media/archive/190-img-7660.webp",
    "alt": "Ein Gruppenportrait mit Menschen, die den Hochzeitstag begleitet haben – Aufnahme 190",
    "width": 2000,
    "height": 1333,
    "chapter": "Unsere Familien und Freunde",
    "layout": "standard"
  },
  {
    "id": "archive-191-img-7667",
    "src": "/media/archive/191-img-7667.webp",
    "alt": "Familie, Freunde und das Brautpaar im Schlossgarten – Aufnahme 191",
    "width": 1333,
    "height": 2000,
    "chapter": "Unsere Familien und Freunde",
    "layout": "portrait"
  },
  {
    "id": "archive-192-img-7671",
    "src": "/media/archive/192-img-7671.webp",
    "alt": "Lea und Christoph gemeinsam mit Familie und Freunden – Aufnahme 192",
    "width": 2000,
    "height": 1333,
    "chapter": "Unsere Familien und Freunde",
    "layout": "standard"
  },
  {
    "id": "archive-193-img-7679",
    "src": "/media/archive/193-img-7679.webp",
    "alt": "Ein Gruppenportrait mit Menschen, die den Hochzeitstag begleitet haben – Aufnahme 193",
    "width": 2000,
    "height": 1333,
    "chapter": "Unsere Familien und Freunde",
    "layout": "wide"
  },
  {
    "id": "archive-194-img-7681",
    "src": "/media/archive/194-img-7681.webp",
    "alt": "Familie, Freunde und das Brautpaar im Schlossgarten – Aufnahme 194",
    "width": 2000,
    "height": 1333,
    "chapter": "Unsere Familien und Freunde",
    "layout": "standard"
  },
  {
    "id": "archive-195-img-7687",
    "src": "/media/archive/195-img-7687.webp",
    "alt": "Lea und Christoph gemeinsam mit Familie und Freunden – Aufnahme 195",
    "width": 2000,
    "height": 1333,
    "chapter": "Unsere Familien und Freunde",
    "layout": "standard"
  },
  {
    "id": "archive-196-img-7701",
    "src": "/media/archive/196-img-7701.webp",
    "alt": "Ein Gruppenportrait mit Menschen, die den Hochzeitstag begleitet haben – Aufnahme 196",
    "width": 1333,
    "height": 2000,
    "chapter": "Unsere Familien und Freunde",
    "layout": "full"
  },
  {
    "id": "archive-197-img-7716",
    "src": "/media/archive/197-img-7716.webp",
    "alt": "Familie, Freunde und das Brautpaar im Schlossgarten – Aufnahme 197",
    "width": 2000,
    "height": 1310,
    "chapter": "Unsere Familien und Freunde",
    "layout": "wide"
  },
  {
    "id": "archive-198-img-7719",
    "src": "/media/archive/198-img-7719.webp",
    "alt": "Lea und Christoph gemeinsam mit Familie und Freunden – Aufnahme 198",
    "width": 2000,
    "height": 1376,
    "chapter": "Unsere Familien und Freunde",
    "layout": "standard"
  },
  {
    "id": "archive-199-img-7724",
    "src": "/media/archive/199-img-7724.webp",
    "alt": "Ein Gruppenportrait mit Menschen, die den Hochzeitstag begleitet haben – Aufnahme 199",
    "width": 2000,
    "height": 1333,
    "chapter": "Unsere Familien und Freunde",
    "layout": "standard"
  },
  {
    "id": "archive-200-img-7733",
    "src": "/media/archive/200-img-7733.webp",
    "alt": "Familie, Freunde und das Brautpaar im Schlossgarten – Aufnahme 200",
    "width": 2000,
    "height": 1333,
    "chapter": "Unsere Familien und Freunde",
    "layout": "standard"
  },
  {
    "id": "archive-201-img-7735",
    "src": "/media/archive/201-img-7735.webp",
    "alt": "Lea und Christoph gemeinsam mit Familie und Freunden – Aufnahme 201",
    "width": 2000,
    "height": 1333,
    "chapter": "Unsere Familien und Freunde",
    "layout": "wide"
  },
  {
    "id": "archive-202-img-7738",
    "src": "/media/archive/202-img-7738.webp",
    "alt": "Ein Gruppenportrait mit Menschen, die den Hochzeitstag begleitet haben – Aufnahme 202",
    "width": 1259,
    "height": 2000,
    "chapter": "Unsere Familien und Freunde",
    "layout": "portrait"
  },
  {
    "id": "archive-203-img-7740",
    "src": "/media/archive/203-img-7740.webp",
    "alt": "Familie, Freunde und das Brautpaar im Schlossgarten – Aufnahme 203",
    "width": 2000,
    "height": 1333,
    "chapter": "Unsere Familien und Freunde",
    "layout": "standard"
  },
  {
    "id": "archive-204-img-7741",
    "src": "/media/archive/204-img-7741.webp",
    "alt": "Lea und Christoph gemeinsam mit Familie und Freunden – Aufnahme 204",
    "width": 2000,
    "height": 1333,
    "chapter": "Unsere Familien und Freunde",
    "layout": "standard"
  },
  {
    "id": "archive-205-img-7742",
    "src": "/media/archive/205-img-7742.webp",
    "alt": "Ein Gruppenportrait mit Menschen, die den Hochzeitstag begleitet haben – Aufnahme 205",
    "width": 2000,
    "height": 1333,
    "chapter": "Unsere Familien und Freunde",
    "layout": "quiet"
  },
  {
    "id": "archive-206-img-7745",
    "src": "/media/archive/206-img-7745.webp",
    "alt": "Familie, Freunde und das Brautpaar im Schlossgarten – Aufnahme 206",
    "width": 2000,
    "height": 1333,
    "chapter": "Unsere Familien und Freunde",
    "layout": "standard"
  },
  {
    "id": "archive-207-img-7746",
    "src": "/media/archive/207-img-7746.webp",
    "alt": "Lea und Christoph gemeinsam mit Familie und Freunden – Aufnahme 207",
    "width": 2000,
    "height": 1333,
    "chapter": "Unsere Familien und Freunde",
    "layout": "standard"
  },
  {
    "id": "archive-208-img-7751",
    "src": "/media/archive/208-img-7751.webp",
    "alt": "Ein Gruppenportrait mit Menschen, die den Hochzeitstag begleitet haben – Aufnahme 208",
    "width": 1333,
    "height": 2000,
    "chapter": "Unsere Familien und Freunde",
    "layout": "portrait"
  },
  {
    "id": "archive-209-img-7754",
    "src": "/media/archive/209-img-7754.webp",
    "alt": "Familie, Freunde und das Brautpaar im Schlossgarten – Aufnahme 209",
    "width": 2000,
    "height": 1333,
    "chapter": "Unsere Familien und Freunde",
    "layout": "wide"
  },
  {
    "id": "archive-210-img-7756",
    "src": "/media/archive/210-img-7756.webp",
    "alt": "Lea und Christoph gemeinsam mit Familie und Freunden – Aufnahme 210",
    "width": 2000,
    "height": 1333,
    "chapter": "Unsere Familien und Freunde",
    "layout": "standard"
  },
  {
    "id": "archive-211-img-7759",
    "src": "/media/archive/211-img-7759.webp",
    "alt": "Ein Gruppenportrait mit Menschen, die den Hochzeitstag begleitet haben – Aufnahme 211",
    "width": 2000,
    "height": 1333,
    "chapter": "Unsere Familien und Freunde",
    "layout": "standard"
  },
  {
    "id": "archive-212-img-7764",
    "src": "/media/archive/212-img-7764.webp",
    "alt": "Familie, Freunde und das Brautpaar im Schlossgarten – Aufnahme 212",
    "width": 2000,
    "height": 1333,
    "chapter": "Unsere Familien und Freunde",
    "layout": "standard"
  },
  {
    "id": "archive-213-img-7766",
    "src": "/media/archive/213-img-7766.webp",
    "alt": "Lea und Christoph gemeinsam mit Familie und Freunden – Aufnahme 213",
    "width": 2000,
    "height": 1333,
    "chapter": "Unsere Familien und Freunde",
    "layout": "wide"
  }
] as const satisfies readonly GalleryImage[];
